<?php

declare(strict_types=1);

return [
    [
        'code' => 'true-admin.examples',
        'title' => 'Demo',
        'path' => '/examples',
        'icon' => 'true-admin.examples.logo',
        'sort' => 9000,
        'type' => 'directory',
    ],
    [
        'code' => 'true-admin.examples.permission',
        'title' => 'Permission Demo',
        'path' => '/examples/permission',
        'parent' => 'true-admin.examples',
        'icon' => 'LockOutlined',
        'sort' => 10,
        'type' => 'menu',
    ],
    [
        'code' => 'true-admin.examples.loading',
        'title' => 'Loading Demo',
        'path' => '/examples/loading',
        'parent' => 'true-admin.examples',
        'icon' => 'SyncOutlined',
        'sort' => 20,
        'type' => 'menu',
    ],
    [
        'code' => 'true-admin.examples.pageContainer',
        'title' => 'Page Container',
        'path' => '/examples/page-container',
        'parent' => 'true-admin.examples',
        'icon' => 'AppstoreOutlined',
        'sort' => 30,
        'type' => 'menu',
    ],
    [
        'code' => 'true-admin.examples.crud',
        'title' => 'CRUD Page',
        'path' => '/examples/crud',
        'parent' => 'true-admin.examples',
        'icon' => 'TableOutlined',
        'sort' => 40,
        'type' => 'menu',
    ],
    [
        'code' => 'true-admin.examples.components',
        'title' => 'Components',
        'path' => '/examples/components',
        'parent' => 'true-admin.examples',
        'icon' => 'AppstoreOutlined',
        'sort' => 43,
        'type' => 'directory',
    ],
    [
        'code' => 'true-admin.examples.formControls',
        'title' => 'Form Controls',
        'path' => '/examples/form-controls',
        'parent' => 'true-admin.examples.components',
        'icon' => 'AppstoreOutlined',
        'sort' => 10,
        'type' => 'menu',
    ],
    [
        'code' => 'true-admin.examples.attachments',
        'title' => 'Attachments',
        'path' => '/examples/attachments',
        'parent' => 'true-admin.examples.components',
        'icon' => 'AppstoreOutlined',
        'sort' => 20,
        'type' => 'menu',
    ],
    [
        'code' => 'true-admin.examples.display',
        'title' => 'Display',
        'path' => '/examples/display',
        'parent' => 'true-admin.examples.components',
        'icon' => 'AppstoreOutlined',
        'sort' => 30,
        'type' => 'menu',
    ],
    [
        'code' => 'true-admin.examples.markdown',
        'title' => 'Markdown',
        'path' => '/examples/markdown',
        'parent' => 'true-admin.examples.components',
        'icon' => 'AppstoreOutlined',
        'sort' => 35,
        'type' => 'menu',
    ],
    [
        'code' => 'true-admin.examples.actions',
        'title' => 'Actions',
        'path' => '/examples/actions',
        'parent' => 'true-admin.examples.components',
        'icon' => 'AppstoreOutlined',
        'sort' => 40,
        'type' => 'menu',
    ],
    [
        'code' => 'true-admin.examples.audit',
        'title' => 'Audit Logs',
        'path' => '/examples/audit',
        'parent' => 'true-admin.examples.components',
        'icon' => 'AppstoreOutlined',
        'sort' => 50,
        'type' => 'menu',
    ],
    [
        'code' => 'true-admin.examples.selector',
        'title' => 'Selector',
        'path' => '/examples/selector',
        'parent' => 'true-admin.examples',
        'icon' => 'AppstoreOutlined',
        'sort' => 45,
        'type' => 'menu',
    ],
    [
        'code' => 'true-admin.examples.stream',
        'title' => 'Stream Response',
        'path' => '/examples/stream',
        'parent' => 'true-admin.examples',
        'icon' => 'SyncOutlined',
        'sort' => 47,
        'type' => 'menu',
    ],
    [
        'code' => 'true-admin.examples.notification',
        'title' => 'Notifications',
        'path' => '/examples/notification',
        'parent' => 'true-admin.examples',
        'icon' => 'BellOutlined',
        'sort' => 48,
        'type' => 'menu',
    ],
    [
        'code' => 'true-admin.examples.complexForm',
        'title' => 'Complex Form',
        'path' => '/examples/complex-form',
        'parent' => 'true-admin.examples',
        'icon' => 'AppstoreOutlined',
        'sort' => 50,
        'type' => 'menu',
    ],
    [
        'code' => 'true-admin.examples.complexDetail',
        'title' => 'Complex Detail',
        'path' => '/examples/complex-detail',
        'parent' => 'true-admin.examples',
        'icon' => 'AppstoreOutlined',
        'sort' => 60,
        'type' => 'menu',
    ],
    [
        'code' => 'true-admin.examples.multilevel',
        'title' => 'Multi-level Menu',
        'path' => '/examples/multilevel',
        'parent' => 'true-admin.examples',
        'icon' => 'AppstoreOutlined',
        'sort' => 70,
        'type' => 'directory',
    ],
    [
        'code' => 'true-admin.examples.multilevel.second',
        'title' => 'Second Level',
        'path' => '/examples/multilevel/second',
        'parent' => 'true-admin.examples.multilevel',
        'icon' => 'AppstoreOutlined',
        'sort' => 10,
        'type' => 'directory',
    ],
    [
        'code' => 'true-admin.examples.multilevel.second.third',
        'title' => 'Third Level',
        'path' => '/examples/multilevel/second/third',
        'parent' => 'true-admin.examples.multilevel.second',
        'icon' => 'AppstoreOutlined',
        'sort' => 10,
        'type' => 'menu',
    ],
];
