import { existsSync } from 'node:fs';
import { mkdir, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const webRoot = path.resolve(path.dirname(__filename), '..');
const srcRoot = path.join(webRoot, 'src');
const umiLocalesRoot = path.join(srcRoot, 'locales');
const foundationLocaleRoot = path.join(srcRoot, 'foundation', 'locale');
const frameworkRoot = path.join(foundationLocaleRoot, 'framework');

async function discoverFrameworkLocales() {
  if (!existsSync(frameworkRoot)) return [];
  const files = await readdir(frameworkRoot);
  return files
    .map((file) => file.match(/^([a-z]{2}-[A-Z]{2})\.ts$/)?.[1])
    .filter(Boolean)
    .sort((a, b) => a.localeCompare(b));
}

async function generateUmiLocaleEntry(locale) {
  const content = `// This file is generated by scripts/generate-locales.mjs. Do not edit manually.
export { default } from '@/foundation/locale/framework/${locale}';
`;
  await writeFile(path.join(umiLocalesRoot, `${locale}.ts`), content, 'utf8');
}

async function main() {
  await mkdir(umiLocalesRoot, { recursive: true });
  await mkdir(foundationLocaleRoot, { recursive: true });

  const frameworkLocales = await discoverFrameworkLocales();

  for (const locale of frameworkLocales) {
    await generateUmiLocaleEntry(locale);
  }
  console.log(`Generated Umi locale entries: ${frameworkLocales.join(', ') || 'none'}`);
}

await main();
