import { existsSync } from 'node:fs';
import { mkdir, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const webRoot = path.resolve(path.dirname(__filename), '..');
const srcRoot = path.join(webRoot, 'src');
const modulesRoot = path.join(srcRoot, 'modules');
const umiLocalesRoot = path.join(srcRoot, 'locales');
const foundationLocaleRoot = path.join(srcRoot, 'foundation', 'locale');
const frameworkRoot = path.join(foundationLocaleRoot, 'framework');
const moduleRegistryFile = path.join(foundationLocaleRoot, 'moduleLocaleRegistry.generated.ts');

function toImportName(moduleName) {
  const name = moduleName
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, char) => char.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, '');
  return /^[a-zA-Z_]/.test(name) ? name : `_${name}`;
}

async function listModules() {
  if (!existsSync(modulesRoot)) return [];
  const entries = await readdir(modulesRoot, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));
}

async function discoverFrameworkLocales() {
  if (!existsSync(frameworkRoot)) return [];
  const files = await readdir(frameworkRoot);
  return files
    .map((file) => file.match(/^([a-z]{2}-[A-Z]{2})\.ts$/)?.[1])
    .filter(Boolean)
    .sort((a, b) => a.localeCompare(b));
}

async function discoverModuleLocaleMap(modules) {
  const result = new Map();

  for (const moduleName of modules) {
    const localeDir = path.join(modulesRoot, moduleName, 'locales');
    if (!existsSync(localeDir)) continue;
    const files = await readdir(localeDir);
    const locales = files
      .map((file) => file.match(/^([a-z]{2}-[A-Z]{2})\.ts$/)?.[1])
      .filter(Boolean)
      .sort((a, b) => a.localeCompare(b));

    if (locales.length > 0) {
      result.set(moduleName, locales);
    }
  }

  return result;
}

async function generateUmiLocaleEntry(locale) {
  const content = `// This file is generated by scripts/generate-locales.mjs. Do not edit manually.
export { default } from '@/foundation/locale/framework/${locale}';
`;
  await writeFile(path.join(umiLocalesRoot, `${locale}.ts`), content, 'utf8');
}

async function generateModuleLocaleRegistry(moduleLocaleMap) {
  const moduleEntries = [];

  for (const [moduleName, locales] of moduleLocaleMap.entries()) {
    const localeEntries = locales.map((locale) => {
      return `    '${locale}': () => import('@/modules/${moduleName}/locales/${locale}'),`;
    });

    moduleEntries.push(`  ${JSON.stringify(moduleName)}: {
${localeEntries.join('\n')}
  },`);
  }

  const content = `// This file is generated by scripts/generate-locales.mjs. Do not edit manually.
export type ModuleLocaleLoader = () => Promise<{ default: Record<string, string> }>;

export const moduleLocaleLoaders = {
${moduleEntries.join('\n')}
} as const satisfies Record<string, Record<string, ModuleLocaleLoader>>;

export type ModuleLocaleName = keyof typeof moduleLocaleLoaders;
`;
  await writeFile(moduleRegistryFile, content, 'utf8');
}

async function main() {
  await mkdir(umiLocalesRoot, { recursive: true });
  await mkdir(foundationLocaleRoot, { recursive: true });

  const modules = await listModules();
  const frameworkLocales = await discoverFrameworkLocales();
  const moduleLocaleMap = await discoverModuleLocaleMap(modules);

  for (const locale of frameworkLocales) {
    await generateUmiLocaleEntry(locale);
  }
  await generateModuleLocaleRegistry(moduleLocaleMap);

  console.log(`Generated Umi locale entries: ${frameworkLocales.join(', ') || 'none'}`);
  console.log(`Generated module locale registry: ${[...moduleLocaleMap.keys()].join(', ') || 'none'}`);
}

await main();
