import { existsSync } from 'node:fs';
import { mkdir, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const webRoot = path.resolve(path.dirname(__filename), '..');
const srcRoot = path.join(webRoot, 'src');
const modulesRoot = path.join(srcRoot, 'modules');
const routerRoot = path.join(srcRoot, 'foundation', 'router');
const moduleRoutesFile = path.join(routerRoot, 'moduleRoutes.generated.ts');

function toImportName(moduleName) {
  const name = moduleName
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, char) => char.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, '');
  return /^[a-zA-Z_]/.test(name) ? name : `_${name}`;
}

async function discoverRouteModules() {
  if (!existsSync(modulesRoot)) return [];
  const entries = await readdir(modulesRoot, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((moduleName) => existsSync(path.join(modulesRoot, moduleName, 'routes.ts')))
    .sort((a, b) => a.localeCompare(b));
}

async function generateModuleRoutes(routeModules) {
  const imports = routeModules.map((moduleName) => {
    return `import ${toImportName(moduleName)}Routes from '../../modules/${moduleName}/routes';`;
  });

  const spreads = routeModules.map((moduleName) => `  ...${toImportName(moduleName)}Routes,`);

  const content = `// This file is generated by scripts/generate-routes.mjs. Do not edit manually.
${imports.join('\n')}

export const moduleRoutes = [
${spreads.join('\n')}
];

export default moduleRoutes;
`;

  await writeFile(moduleRoutesFile, content, 'utf8');
}

async function main() {
  await mkdir(routerRoot, { recursive: true });
  const routeModules = await discoverRouteModules();
  await generateModuleRoutes(routeModules);
  console.log(`Generated module routes: ${routeModules.join(', ') || 'none'}`);
}

await main();
