import { lazy } from 'react';
import { defineModule } from '@/core/module/types';

export default defineModule({
  id: 'demo',
  routes: [
    {
      path: '/examples/permission',
      component: lazy(() => import('@/app/pages/PermissionExamplePage')),
      meta: { title: 'demo.permission.title', pageType: 'custom-page', auth: true },
    },
    {
      path: '/examples/loading',
      component: lazy(() => import('./pages/LoadingExamplePage')),
      meta: { title: 'demo.loading.title', pageType: 'custom-page', auth: true },
    },
    {
      path: '/examples/page-container',
      component: lazy(() => import('./pages/PageContainerExamplePage')),
      meta: { title: 'demo.pageContainer.title', pageType: 'custom-page', auth: true },
    },
    {
      path: '/examples/crud',
      component: lazy(() => import('./pages/CrudExamplePage')),
      meta: { title: 'demo.crud.title', pageType: 'crud-page', auth: true },
    },
    {
      path: '/examples/complex-form',
      component: lazy(() => import('./pages/ComplexFormExamplePage')),
      meta: {
        title: 'demo.complexForm.title',
        pageType: 'custom-page',
        auth: true,
        layout: { showFooter: false },
      },
    },
    {
      path: '/examples/complex-detail',
      component: lazy(() => import('./pages/ComplexDetailExamplePage')),
      meta: { title: 'demo.complexDetail.title', pageType: 'custom-page', auth: true },
    },
    {
      path: '/examples/multilevel/second/third',
      component: lazy(() => import('./pages/MultiLevelMenuPage')),
      meta: { title: 'demo.multilevel.title', pageType: 'custom-page', auth: true },
    },
  ],
  menus: [
    {
      code: 'demo',
      title: 'Demo',
      i18n: 'menu.demo',
      path: '/examples',
      icon: 'app',
      type: 'directory',
      status: 'enabled',
      sort: 9000,
      devOnly: true,
      children: [
        {
          code: 'demo.permission',
          title: 'Permission Demo',
          i18n: 'menu.demo.permission',
          path: '/examples/permission',
          icon: 'lock',
          type: 'menu',
          status: 'enabled',
          sort: 10,
        },
        {
          code: 'demo.loading',
          title: 'Loading Demo',
          i18n: 'menu.demo.loading',
          path: '/examples/loading',
          icon: 'sync',
          type: 'menu',
          status: 'enabled',
          sort: 20,
        },
        {
          code: 'demo.pageContainer',
          title: 'Page Container',
          i18n: 'menu.demo.pageContainer',
          path: '/examples/page-container',
          icon: 'app',
          type: 'menu',
          status: 'enabled',
          sort: 30,
        },
        {
          code: 'demo.crud',
          title: 'CRUD Demo',
          i18n: 'menu.demo.crud',
          path: '/examples/crud',
          icon: 'table',
          type: 'menu',
          status: 'enabled',
          sort: 40,
        },
        {
          code: 'demo.complexForm',
          title: 'Complex Form',
          i18n: 'menu.demo.complexForm',
          path: '/examples/complex-form',
          icon: 'app',
          type: 'menu',
          status: 'enabled',
          sort: 50,
        },
        {
          code: 'demo.complexDetail',
          title: 'Complex Detail',
          i18n: 'menu.demo.complexDetail',
          path: '/examples/complex-detail',
          icon: 'app',
          type: 'menu',
          status: 'enabled',
          sort: 60,
        },
        {
          code: 'demo.multilevel',
          title: 'Multi-level Menu',
          i18n: 'menu.demo.multilevel',
          path: '/examples/multilevel',
          icon: 'app',
          type: 'directory',
          status: 'enabled',
          sort: 70,
          children: [
            {
              code: 'demo.multilevel.second',
              title: 'Second Level',
              i18n: 'menu.demo.multilevel.second',
              path: '/examples/multilevel/second',
              icon: 'app',
              type: 'directory',
              status: 'enabled',
              sort: 10,
              children: [
                {
                  code: 'demo.multilevel.second.third',
                  title: 'Third Level',
                  i18n: 'menu.demo.multilevel.third',
                  path: '/examples/multilevel/second/third',
                  icon: 'app',
                  type: 'menu',
                  status: 'enabled',
                  sort: 10,
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  locales: {
    'zh-CN': () => import('./locales/zh-CN'),
    'en-US': () => import('./locales/en-US'),
  },
});
