import {
  AppstoreOutlined,
  BellOutlined,
  DashboardOutlined,
  FileUnknownOutlined,
  LockOutlined,
  MailOutlined,
  MenuOutlined,
  SettingOutlined,
  SyncOutlined,
  TeamOutlined,
  UserOutlined,
} from '@ant-design/icons';

export const defaultIcons = {
  dashboard: <DashboardOutlined />,
  setting: <SettingOutlined />,
  system: <SettingOutlined />,
  'system.departments': <TeamOutlined />,
  'system.users': <UserOutlined />,
  'system.client-users': <UserOutlined />,
  'system.roles': <LockOutlined />,
  'system.menus': <MenuOutlined />,
  'system.messages': <MailOutlined />,
  'system.notificationManagement': <BellOutlined />,
  team: <TeamOutlined />,
  user: <UserOutlined />,
  'client-user': <UserOutlined />,
  lock: <LockOutlined />,
  menu: <MenuOutlined />,
  message: <MailOutlined />,
  bell: <BellOutlined />,
  sync: <SyncOutlined />,
  app: <AppstoreOutlined />,
  fallback: <FileUnknownOutlined />,
};
