<?php

declare(strict_types=1);

// This file is generated by trueadmin plugin sync. Do not edit manually.

return [
    'installed' => [
        'true-admin.examples' => [
            'path' => BASE_PATH . '/plugins/true-admin/examples',
            'version' => '0.1.0',
            'enabled' => false,
            'defaults' => [],
        ],
    ],
    'disabled' => [],
    'config' => [],
];
