// This file is generated by trueadmin plugin sync. Do not edit manually.
import type { PluginRuntimeConfig } from '@trueadmin/web-core/plugin';

export const pluginConfig: Record<string, PluginRuntimeConfig> = {
  'true-admin.examples': {
    enabled: true,
  },
};
