<?php

declare(strict_types=1);
/**
 * This file is part of Hyperf.
 *
 * @link     https://www.hyperf.io
 * @document https://hyperf.wiki
 * @contact  group@hyperf.io
 * @license  https://github.com/hyperf/hyperf/blob/master/LICENSE
 */
return [
    [
        'code' => 'workbench',
        'title' => '工作台',
        'path' => '/workbench',
        'icon' => 'DashboardOutlined',
        'sort' => -100,
        'type' => 'menu',
    ],
    [
        'code' => 'organization',
        'title' => '组织权限',
        'path' => '/organization',
        'icon' => 'ApartmentOutlined',
        'sort' => 30,
        'type' => 'directory',
    ],
    [
        'code' => 'system.departments',
        'title' => '部门管理',
        'path' => '/organization/departments',
        'parent' => 'organization',
        'permission' => 'system:department:list',
        'icon' => 'TeamOutlined',
        'sort' => 10,
        'type' => 'menu',
    ],
    [
        'code' => 'system.departments.detail',
        'title' => '部门详情',
        'parent' => 'system.departments',
        'permission' => 'system:department:detail',
        'sort' => 11,
        'type' => 'button',
    ],
    [
        'code' => 'system.departments.create',
        'title' => '新增部门',
        'parent' => 'system.departments',
        'permission' => 'system:department:create',
        'sort' => 12,
        'type' => 'button',
    ],
    [
        'code' => 'system.departments.update',
        'title' => '编辑部门',
        'parent' => 'system.departments',
        'permission' => 'system:department:update',
        'sort' => 13,
        'type' => 'button',
    ],
    [
        'code' => 'system.departments.delete',
        'title' => '删除部门',
        'parent' => 'system.departments',
        'permission' => 'system:department:delete',
        'sort' => 14,
        'type' => 'button',
    ],
    [
        'code' => 'system.users',
        'title' => '成员管理',
        'path' => '/organization/users',
        'parent' => 'organization',
        'permission' => 'system:user:list',
        'icon' => 'UserOutlined',
        'sort' => 50,
        'type' => 'menu',
    ],
    [
        'code' => 'system.users.detail',
        'title' => '成员详情',
        'parent' => 'system.users',
        'permission' => 'system:user:detail',
        'sort' => 21,
        'type' => 'button',
    ],
    [
        'code' => 'system.users.create',
        'title' => '新增成员',
        'parent' => 'system.users',
        'permission' => 'system:user:create',
        'sort' => 22,
        'type' => 'button',
    ],
    [
        'code' => 'system.users.update',
        'title' => '编辑成员',
        'parent' => 'system.users',
        'permission' => 'system:user:update',
        'sort' => 23,
        'type' => 'button',
    ],
    [
        'code' => 'system.users.delete',
        'title' => '删除成员',
        'parent' => 'system.users',
        'permission' => 'system:user:delete',
        'sort' => 24,
        'type' => 'button',
    ],
    [
        'code' => 'system.positions',
        'title' => '岗位管理',
        'path' => '/organization/positions',
        'parent' => 'organization',
        'permission' => 'system:position:list',
        'icon' => 'IdcardOutlined',
        'sort' => 25,
        'type' => 'button',
    ],
    [
        'code' => 'system.positions.detail',
        'title' => '岗位详情',
        'parent' => 'system.positions',
        'permission' => 'system:position:detail',
        'sort' => 26,
        'type' => 'button',
    ],
    [
        'code' => 'system.positions.create',
        'title' => '新增岗位',
        'parent' => 'system.positions',
        'permission' => 'system:position:create',
        'sort' => 27,
        'type' => 'button',
    ],
    [
        'code' => 'system.positions.update',
        'title' => '编辑岗位',
        'parent' => 'system.positions',
        'permission' => 'system:position:update',
        'sort' => 28,
        'type' => 'button',
    ],
    [
        'code' => 'system.positions.delete',
        'title' => '删除岗位',
        'parent' => 'system.positions',
        'permission' => 'system:position:delete',
        'sort' => 29,
        'type' => 'button',
    ],
    [
        'code' => 'system.roles',
        'title' => '角色管理',
        'path' => '/organization/roles',
        'parent' => 'organization',
        'permission' => 'system:role:list',
        'icon' => 'LockOutlined',
        'sort' => 30,
        'type' => 'menu',
    ],
    [
        'code' => 'system.roles.detail',
        'title' => '角色详情',
        'parent' => 'system.roles',
        'permission' => 'system:role:detail',
        'sort' => 31,
        'type' => 'button',
    ],
    [
        'code' => 'system.roles.create',
        'title' => '新增角色',
        'parent' => 'system.roles',
        'permission' => 'system:role:create',
        'sort' => 32,
        'type' => 'button',
    ],
    [
        'code' => 'system.roles.update',
        'title' => '编辑角色',
        'parent' => 'system.roles',
        'permission' => 'system:role:update',
        'sort' => 33,
        'type' => 'button',
    ],
    [
        'code' => 'system.roles.delete',
        'title' => '删除角色',
        'parent' => 'system.roles',
        'permission' => 'system:role:delete',
        'sort' => 34,
        'type' => 'button',
    ],
    [
        'code' => 'system.roles.authorize',
        'title' => '角色授权',
        'parent' => 'system.roles',
        'permission' => 'system:role:authorize',
        'sort' => 35,
        'type' => 'button',
    ],
    [
        'code' => 'system.clientUsers',
        'title' => '用户端账号',
        'path' => '/organization/client-users',
        'parent' => 'organization',
        'permission' => 'system:client-user:list',
        'icon' => 'UserOutlined',
        'sort' => 90,
        'type' => 'menu',
        'status' => 'disabled',
    ],
    [
        'code' => 'system.clientUsers.detail',
        'title' => '用户端账号详情',
        'parent' => 'system.clientUsers',
        'permission' => 'system:client-user:detail',
        'sort' => 91,
        'type' => 'button',
    ],
    [
        'code' => 'system.clientUsers.create',
        'title' => '新增用户端账号',
        'parent' => 'system.clientUsers',
        'permission' => 'system:client-user:create',
        'sort' => 92,
        'type' => 'button',
    ],
    [
        'code' => 'system.clientUsers.update',
        'title' => '编辑用户端账号',
        'parent' => 'system.clientUsers',
        'permission' => 'system:client-user:update',
        'sort' => 93,
        'type' => 'button',
    ],
    [
        'code' => 'system.clientUsers.delete',
        'title' => '删除用户端账号',
        'parent' => 'system.clientUsers',
        'permission' => 'system:client-user:delete',
        'sort' => 94,
        'type' => 'button',
    ],
    [
        'code' => 'system.clientUsers.status',
        'title' => '用户端账号状态',
        'parent' => 'system.clientUsers',
        'permission' => 'system:client-user:status',
        'sort' => 95,
        'type' => 'button',
    ],
    [
        'code' => 'system.messages',
        'title' => '消息中心',
        'path' => '/messages',
        'permission' => 'system:message:list',
        'icon' => 'MailOutlined',
        'sort' => 20,
        'type' => 'menu',
    ],
    [
        'code' => 'system.messages.detail',
        'title' => '消息详情',
        'parent' => 'system.messages',
        'permission' => 'system:message:detail',
        'sort' => 21,
        'type' => 'button',
    ],
    [
        'code' => 'system.messages.update',
        'title' => '消息操作',
        'parent' => 'system.messages',
        'permission' => 'system:message:update',
        'sort' => 22,
        'type' => 'button',
    ],
    [
        'code' => 'messageManagement',
        'title' => '消息管理',
        'path' => '/message-management',
        'icon' => 'NotificationOutlined',
        'sort' => 40,
        'type' => 'directory',
    ],
    [
        'code' => 'system.announcementManagement',
        'title' => '公告管理',
        'path' => '/message-management/announcements',
        'parent' => 'messageManagement',
        'permission' => 'system:announcement:list',
        'icon' => 'NotificationOutlined',
        'sort' => 10,
        'type' => 'menu',
    ],
    [
        'code' => 'system.announcementManagement.detail',
        'title' => '公告详情',
        'parent' => 'system.announcementManagement',
        'permission' => 'system:announcement:detail',
        'sort' => 11,
        'type' => 'button',
    ],
    [
        'code' => 'system.announcementManagement.create',
        'title' => '创建公告',
        'parent' => 'system.announcementManagement',
        'permission' => 'system:announcement:create',
        'sort' => 12,
        'type' => 'button',
    ],
    [
        'code' => 'system.announcementManagement.update',
        'title' => '编辑公告',
        'parent' => 'system.announcementManagement',
        'permission' => 'system:announcement:update',
        'sort' => 13,
        'type' => 'button',
    ],
    [
        'code' => 'system.announcementManagement.delete',
        'title' => '删除公告草稿',
        'parent' => 'system.announcementManagement',
        'permission' => 'system:announcement:delete',
        'sort' => 14,
        'type' => 'button',
    ],
    [
        'code' => 'system.announcementManagement.publish',
        'title' => '发布公告',
        'parent' => 'system.announcementManagement',
        'permission' => 'system:announcement:publish',
        'sort' => 15,
        'type' => 'button',
    ],
    [
        'code' => 'system.announcementManagement.offline',
        'title' => '下线公告',
        'parent' => 'system.announcementManagement',
        'permission' => 'system:announcement:offline',
        'sort' => 16,
        'type' => 'button',
    ],
    [
        'code' => 'system.notificationManagement',
        'title' => '通知管理',
        'path' => '/message-management/notifications',
        'parent' => 'messageManagement',
        'permission' => 'system:notification:list',
        'icon' => 'BellOutlined',
        'sort' => 20,
        'type' => 'menu',
    ],
    [
        'code' => 'system.notificationManagement.detail',
        'title' => '通知详情',
        'parent' => 'system.notificationManagement',
        'permission' => 'system:notification:detail',
        'sort' => 21,
        'type' => 'button',
    ],
    [
        'code' => 'system.notificationManagement.deliveryList',
        'title' => '通知投递记录',
        'parent' => 'system.notificationManagement',
        'permission' => 'system:notification:delivery:list',
        'sort' => 22,
        'type' => 'button',
    ],
    [
        'code' => 'system.notificationManagement.deliveryResend',
        'title' => '重发通知',
        'parent' => 'system.notificationManagement',
        'permission' => 'system:notification:delivery:resend',
        'sort' => 23,
        'type' => 'button',
    ],
    [
        'code' => 'systemConfig',
        'title' => '系统配置',
        'path' => '/system-config',
        'icon' => 'SettingOutlined',
        'sort' => 90,
        'type' => 'directory',
    ],
    [
        'code' => 'system.menus',
        'title' => '菜单管理',
        'path' => '/system-config/menus',
        'parent' => 'systemConfig',
        'permission' => 'system:menu:list',
        'icon' => 'MenuOutlined',
        'sort' => 10,
        'type' => 'menu',
    ],
    [
        'code' => 'system.menus.detail',
        'title' => '菜单详情',
        'parent' => 'system.menus',
        'permission' => 'system:menu:detail',
        'sort' => 11,
        'type' => 'button',
    ],
    [
        'code' => 'system.menus.create',
        'title' => '新增菜单',
        'parent' => 'system.menus',
        'permission' => 'system:menu:create',
        'sort' => 12,
        'type' => 'button',
    ],
    [
        'code' => 'system.menus.update',
        'title' => '编辑菜单',
        'parent' => 'system.menus',
        'permission' => 'system:menu:update',
        'sort' => 13,
        'type' => 'button',
    ],
    [
        'code' => 'system.menus.delete',
        'title' => '删除菜单',
        'parent' => 'system.menus',
        'permission' => 'system:menu:delete',
        'sort' => 14,
        'type' => 'button',
    ],
    [
        'code' => 'system.permissions',
        'title' => '权限点',
        'parent' => 'systemConfig',
        'permission' => 'system:permission:list',
        'sort' => 20,
        'type' => 'button',
    ],
    [
        'code' => 'system.files.list',
        'title' => '文件列表',
        'parent' => 'systemConfig',
        'permission' => 'system:file:list',
        'sort' => 30,
        'type' => 'button',
    ],
    [
        'code' => 'system.files.detail',
        'title' => '文件详情',
        'parent' => 'systemConfig',
        'permission' => 'system:file:detail',
        'sort' => 31,
        'type' => 'button',
    ],
    [
        'code' => 'system.files.upload',
        'title' => '上传文件',
        'parent' => 'systemConfig',
        'permission' => 'system:file:upload',
        'sort' => 32,
        'type' => 'button',
    ],
    [
        'code' => 'system.files.all',
        'title' => '全部文件权限',
        'parent' => 'systemConfig',
        'permission' => 'system:file:all',
        'sort' => 33,
        'type' => 'button',
    ],
    [
        'code' => 'system.loginLogs',
        'title' => '登录日志',
        'path' => '/system-config/login-logs',
        'icon' => 'LoginOutlined',
        'parent' => 'systemConfig',
        'permission' => 'system:login-log:list',
        'sort' => 80,
        'type' => 'menu',
    ],
    [
        'code' => 'system.loginLogs.detail',
        'title' => '登录日志详情',
        'parent' => 'system.loginLogs',
        'permission' => 'system:login-log:detail',
        'sort' => 81,
        'type' => 'button',
    ],
    [
        'code' => 'system.operationLogs',
        'title' => '操作日志',
        'path' => '/system-config/operation-logs',
        'icon' => 'AuditOutlined',
        'parent' => 'systemConfig',
        'permission' => 'system:operation-log:list',
        'sort' => 90,
        'type' => 'menu',
    ],
    [
        'code' => 'system.operationLogs.detail',
        'title' => '操作日志详情',
        'parent' => 'system.operationLogs',
        'permission' => 'system:operation-log:detail',
        'sort' => 91,
        'type' => 'button',
    ],
];
